force-app/main/default/objects/Greenhouse_Integration_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Error_Email_Notifications__c</fullName>
        <label>Error Email Notifications</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Greenhouse Integration Settings</label>
</CustomObject>

force-app/main/default/objects/Sync_Log__c.object
<CustomObject>
    <fields>
        <fullName>Applications_Synced__c</fullName>
        <label>Applications Synced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Candidates_Synced__c</fullName>
        <label>Candidates Synced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jobs_Synced__c</fullName>
        <label>Jobs Synced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Greenhouse Sync Log</label>
    <nameField>
        <displayFormat>SNL-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Greenhouse Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/queueable_SyncGreenhouseApplication.cls
public class queueable_SyncGreenhouseApplication implements Queueable { 
    
    private Integer pageCount;
    private Sync_Log__c syncLog;
    
    public queueable_SyncGreenhouseApplication(Integer pageCount, Sync_Log__c syncLog){
        this.pageCount = pageCount;
        this.syncLog = syncLog;
    }
    
    public void execute(QueueableContext context) {
        
        Integer noOfApplicationsProcessed = greenhouseApiHelper.greenhouseJobs(null,pageCount);
        syncLog.Applications_Synced__c += noOfApplicationsProcessed;
        
        if(noOfApplicationsProcessed == 50 && pageCount < 4){
            System.enqueueJob(new queueable_SyncGreenhouseApplication(pageCount++, syncLog));
        }
        else{
            insert syncLog;
            
            Greenhouse_Integration_Settings__c greenhouseSetting = Greenhouse_Integration_Settings__c.getOrgDefaults();
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {greenhouseSetting.Error_Email_Notifications__c};
            mail.setToAddresses(toAddresses);
            mail.setSubject('Batch Status');
            mail.setHtmlBody('Hi,<br/><br/> Your Sync batch is processed Successfully <br/><br/> Candidates Processed: ' + syncLog.Candidates_Synced__c + ' <br/><br/> Jobs Processed: ' + syncLog.Jobs_Synced__c + ' <br/><br/> Applications Processed: ' + syncLog.Applications_Synced__c);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
        
    }
}