force-app/main/default/objects/Sync_Log__c.object
<CustomObject>
    <fields>
        <fullName>Applications_Synced__c</fullName>
        <label>Applications Synced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Candidates_Synced__c</fullName>
        <label>Candidates Synced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jobs_Synced__c</fullName>
        <label>Jobs Synced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Date_Time__c</fullName>
        <label>Last Sync Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Greenhouse Sync Log</label>
    <nameField>
        <displayFormat>SNL-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Greenhouse Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/queueable_SyncGreenhouseCandidate.cls
public class queueable_SyncGreenhouseCandidate implements Queueable { 
    
    private Integer pageCount;
    private Sync_Log__c syncLog;
    
    public queueable_SyncGreenhouseCandidate(Integer pageCount){
        this.pageCount = pageCount;
        this.syncLog = new Sync_Log__c(Candidates_Synced__c = 0, Jobs_Synced__c = 0, Applications_Synced__c = 0, Last_Sync_Date_Time__c = Datetime.Now());
    }
    
    public queueable_SyncGreenhouseCandidate(Integer pageCount, Sync_Log__c syncLog){
        this.pageCount = pageCount;
        this.syncLog = syncLog;
    }
    
    public void execute(QueueableContext context) {
        
        Integer noOfCandidatesProcessed = greenhouseApiHelper.greenhouseCandidates(null,pageCount);
        syncLog.Candidates_Synced__c += noOfCandidatesProcessed;
        
        if(noOfCandidatesProcessed == 50 && pageCount < 4){
             
            System.enqueueJob(new queueable_SyncGreenhouseCandidate(pageCount++, syncLog));
        }
        else{
            System.enqueueJob(new queueable_SyncGreenhouseJob(1, syncLog));
        }
        
    }
}