force-app/main/default/objects/Sync_Log__c.object
<CustomObject>
    <fields>
        <fullName>Jobs_Synced__c</fullName>
        <label>Jobs Synced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Greenhouse Sync Log</label>
    <nameField>
        <displayFormat>SNL-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Greenhouse Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/queueable_SyncGreenhouseJob.cls
public class queueable_SyncGreenhouseJob implements Queueable { 
    
    private Integer pageCount;
    private Sync_Log__c syncLog;
    
    public queueable_SyncGreenhouseJob(Integer pageCount, Sync_Log__c syncLog){
        this.pageCount = pageCount;
        this.syncLog = syncLog;
    }
    
    public void execute(QueueableContext context) {
        
        Integer noOfJobsProcessed = greenhouseApiHelper.greenhouseJobs(null,pageCount);
        syncLog.Jobs_Synced__c += noOfJobsProcessed;
        
        if(noOfJobsProcessed == 50 && pageCount < 4){
            System.enqueueJob(new queueable_SyncGreenhouseJob(pageCount++, syncLog));
        }
        else{
            System.enqueueJob(new queueable_SyncGreenhouseApplication(1, syncLog));
        }
        
    }
}